const tileOptions = [
  'Walrus',
  'Cigarettes',
  'Liquor',
  'Legumes',
  'Screwed up training document',
  'What SOP?',
  'Revalidate',
  'Changing the rules',
  '"The Look"',
  'Kegan is missing',
  'Page entire department',
  'Doof',
  '"This is Nancy talking"',
  'Unqualified Supplier',
  '"What does IRF mean"',
  'Quagga',
  'Printer jam',
  '"Its hot in here"',
  'Fanning the face',
  'Misunderstood page',
  'Unapproved document',
  'Sweating',
  'Crying',
  'Out to lunch',
  'Papercut',
  'Stress eating',
  'Send a runner',
  'Missing equipment',
  'file',
  'RAM not accurate',
  '"Who the hell wrote ____?"',
  'CPP issue',
  'GDP issue',
  'Untrained operator',
  'Cleaning validation',
  'Data Integrity',
  'No traceability',
  'Risk assessment',
  'Pallets',
  'Pest control',
  'Rogue SME',
  'Going in without prep',
  'Unescorted SME',
  'Chair issue',
  'Call IT',
  'Call someone we don\'t need',
  'Taking too long to prep',
  'Special torture',
  'LYO room',
  'Overdue CAPA',
  'Breaking your own rules',
  'cross-contamination',
  'snorkel',
  'alphabetizing',
  'the f-word',
  'wardrobe malfunction',
  'pen tapping',
  'shit show',
  'keegal',
  'incorrect calibration sticker',
  'deflection',
  'bouffant'
];

export default tileOptions;
